### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by AmulGaurav** [marshadkhn/GitPractice#38]
It should be great if we keep track of all the tasks day-wise in the readme itself.

Example:
### Day 1
1. Fork the repo.
2. clone it into your system.
3. create 2 issues and wait to be assigned.
4. after assigned, complete the issue.
5. create PR.

**Comment by AmulGaurav** [comment]
Can I work on this issue??

**Comment by AmulGaurav** [comment]
sure, would love to.

**Comment by marshadkhn** [comment]
Ok buddy
