### ISSUE TITLE
docs: link daily tasks sheet in the Readme.md

### ISSUE THREAD

**Issue by AmulGaurav** [marshadkhn/GitPractice#82]
It is kinda difficult to find the links of the repo and the task sheet separately.

It would be great if we link the [**tasks sheet**](https://docs.google.com/document/d/1WkuNkHiZsEYU7siOYBGcdbrjNEewm52CACUFuzV1ugw/edit) in the **Readme.md**.

**Comment by marshadkhn** [comment]
OK, but it's pinned ig
no need to put here coz it's for only for us

**Comment by AmulGaurav** [comment]
Yeah! But it can be put in the description of the repo, I guess.

**Comment by marshadkhn** [comment]
NO NEED

**Comment by AmulGaurav** [comment]
Sure.
